// AUTO-GENERATED. Lista de nomes brasileiros para autocomplete de cliente.
// Combinação primeiro-nome + sobrenome no autocomplete gera milhares de variações.

export const BR_FIRST_NAMES: readonly string[] = [
  "Maria",
  "Jos\u00e9",
  "Ana",
  "Jo\u00e3o",
  "Antonio",
  "Ant\u00f4nio",
  "Francisco",
  "Carlos",
  "Paulo",
  "Pedro",
  "Lucas",
  "Luiz",
  "Lu\u00eds",
  "Marcos",
  "Gabriel",
  "Rafael",
  "Daniel",
  "Marcelo",
  "Bruno",
  "Eduardo",
  "Felipe",
  "Raimundo",
  "Rodrigo",
  "Manoel",
  "Manuel",
  "Sebasti\u00e3o",
  "Mateus",
  "Matheus",
  "Tiago",
  "Thiago",
  "Gustavo",
  "Andr\u00e9",
  "Adriano",
  "Anderson",
  "Alessandro",
  "Alexandre",
  "Alex",
  "Alfredo",
  "Almir",
  "Alvaro",
  "\u00c1lvaro",
  "Amauri",
  "Amaury",
  "Anselmo",
  "Antenor",
  "Aparecido",
  "Arnaldo",
  "Arthur",
  "Artur",
  "Augusto",
  "Aurelio",
  "Aur\u00e9lio",
  "Benedito",
  "Benicio",
  "Benjamin",
  "Bernardo",
  "Caio",
  "Cassio",
  "C\u00e1ssio",
  "Cesar",
  "C\u00e9sar",
  "Claudio",
  "Cl\u00e1udio",
  "Cleber",
  "Cleiton",
  "Cl\u00f3vis",
  "Cristian",
  "Christian",
  "Cristiano",
  "Davi",
  "David",
  "Dem\u00e9trio",
  "Diego",
  "Dimas",
  "Diogo",
  "Domingos",
  "Donizete",
  "Douglas",
  "Edgar",
  "Edilson",
  "Edmar",
  "Edmilson",
  "Edmundo",
  "Edson",
  "Edvaldo",
  "Eli",
  "Elias",
  "Eliel",
  "Eliseu",
  "Elisio",
  "Elson",
  "Emanuel",
  "Emerson",
  "Enzo",
  "Eraldo",
  "Erasmo",
  "Eric",
  "Erick",
  "Ernesto",
  "Estev\u00e3o",
  "Eurico",
  "Evaldo",
  "Evandro",
  "Everaldo",
  "Everson",
  "Ezequiel",
  "Fabiano",
  "Fabricio",
  "F\u00e1bio",
  "Fabio",
  "Fagner",
  "Fausto",
  "Fel\u00edcio",
  "Fernando",
  "Fernandes",
  "Filipe",
  "Flavio",
  "Fl\u00e1vio",
  "Florisvaldo",
  "Frederico",
  "Gean",
  "Geraldo",
  "Germano",
  "Get\u00falio",
  "Gilberto",
  "Gild\u00e1sio",
  "Gilmar",
  "Gilson",
  "Giovani",
  "Giovanni",
  "Glauber",
  "Glauco",
  "Gledson",
  "Gleidson",
  "Gon\u00e7alo",
  "Guido",
  "Guilherme",
  "Hamilton",
  "Helder",
  "H\u00e9lio",
  "Helio",
  "Heitor",
  "Helton",
  "Henrique",
  "Her\u00e1clito",
  "Heriberto",
  "Hermes",
  "Hil\u00e1rio",
  "Hugo",
  "Humberto",
  "Iago",
  "Igor",
  "Ilan",
  "In\u00e1cio",
  "Iran",
  "Irineu",
  "Isaac",
  "Isa\u00edas",
  "Isidoro",
  "Israel",
  "Italo",
  "Ivan",
  "Ivanildo",
  "Ivo",
  "Jac\u00f3",
  "Jacson",
  "Jair",
  "Jairo",
  "James",
  "Jamil",
  "Janderson",
  "Jeferson",
  "Jefferson",
  "Jeremias",
  "Jer\u00f4nimo",
  "Jess\u00e9",
  "Jhonatan",
  "Joaquim",
  "Joel",
  "Jonas",
  "Jonatas",
  "Jonathan",
  "Jordi",
  "Jorge",
  "Josias",
  "Josu\u00e9",
  "Juarez",
  "J\u00falio",
  "Julio",
  "Junior",
  "J\u00fanior",
  "Kaique",
  "Karlos",
  "Kau\u00e3",
  "Kauan",
  "Kelvin",
  "Kennedy",
  "Kenneth",
  "Kevin",
  "Klaus",
  "Lael",
  "Laercio",
  "La\u00e9rcio",
  "Lauro",
  "Laurentino",
  "Lazaro",
  "L\u00e1zaro",
  "Leandro",
  "Leco",
  "L\u00e9lio",
  "Leo",
  "Leoncio",
  "Leonardo",
  "Leonel",
  "Leopoldo",
  "Levi",
  "Lindolfo",
  "Lindomar",
  "Lino",
  "Lisandro",
  "Livio",
  "L\u00edvio",
  "Lourival",
  "L\u00facio",
  "Lucio",
  "Luciano",
  "Lucindo",
  "Ludovico",
  "Luis",
  "Ot\u00e1vio",
  "Maciel",
  "Marcial",
  "Marciano",
  "Marcio",
  "M\u00e1rcio",
  "Marcondes",
  "Marcus",
  "Vin\u00edcius",
  "Mariano",
  "Mario",
  "M\u00e1rio",
  "Marlon",
  "Martim",
  "Martin",
  "Matias",
  "Mauricio",
  "Maur\u00edcio",
  "Mauro",
  "Maximiliano",
  "Mendes",
  "Michael",
  "Michel",
  "Miguel",
  "Milton",
  "Moacir",
  "Moacyr",
  "Mois\u00e9s",
  "Murilo",
  "Mychel",
  "Nair",
  "Naldo",
  "Natan",
  "Natanael",
  "Nathan",
  "Nelson",
  "Nelmar",
  "N\u00e9sio",
  "Newton",
  "Nicolas",
  "Nicolau",
  "Norberto",
  "Norival",
  "Oct\u00e1vio",
  "Olavo",
  "Oleg\u00e1rio",
  "Oliveiros",
  "Oseas",
  "Osmar",
  "Osmir",
  "Osni",
  "Osvaldo",
  "Otaviano",
  "Otto",
  "Pablo",
  "Patrick",
  "Percival",
  "Pierre",
  "Pl\u00ednio",
  "Pomp\u00edlio",
  "Querino",
  "Quirino",
  "Rael",
  "Rainer",
  "Ramiro",
  "Ramon",
  "Raul",
  "Reinaldo",
  "Reginaldo",
  "R\u00e9gis",
  "Renan",
  "Renato",
  "Ricardo",
  "Ricieri",
  "Rinaldo",
  "Rivelino",
  "Roberto",
  "Robson",
  "Rodolfo",
  "Rog\u00e9rio",
  "Rolando",
  "Romario",
  "Rom\u00e1rio",
  "Romeu",
  "Romildo",
  "Romilson",
  "Romualdo",
  "Romulo",
  "R\u00f4mulo",
  "Ronaldo",
  "Ronan",
  "Ronildo",
  "Roney",
  "Rosalvo",
  "Rubens",
  "Ryan",
  "Sabino",
  "Salom\u00e3o",
  "Salvador",
  "Samuel",
  "Sandro",
  "Saulo",
  "Sergio",
  "S\u00e9rgio",
  "Severiano",
  "Severino",
  "Sidnei",
  "Sidney",
  "Silvano",
  "Silvio",
  "S\u00edlvio",
  "Sim\u00e3o",
  "Sinval",
  "S\u00f3crates",
  "St\u00e9fano",
  "Tadeu",
  "Talles",
  "Tales",
  "Telmo",
  "Teobaldo",
  "Te\u00f3filo",
  "Thales",
  "Theodoro",
  "Thomas",
  "Tito",
  "Tobias",
  "Tom",
  "Tom\u00e1s",
  "T\u00falio",
  "Ubirajara",
  "U\u00edlson",
  "Ulisses",
  "Uriel",
  "Valdecir",
  "Valdeir",
  "Valdemar",
  "Valdir",
  "Valentim",
  "Val\u00e9rio",
  "Valdo",
  "Valter",
  "Vandeir",
  "Vando",
  "Vandeson",
  "Vanderlei",
  "Vargas",
  "Vasco",
  "Vicente",
  "Victor",
  "Vinicius",
  "Virg\u00edlio",
  "Vitor",
  "Wagner",
  "Walace",
  "Walberto",
  "Waldemar",
  "Waldir",
  "Walfrido",
  "Wallace",
  "Walmir",
  "Walter",
  "Wanderley",
  "Washington",
  "Wellington",
  "Wenceslau",
  "Werley",
  "Wesley",
  "Wilian",
  "Williams",
  "Wilson",
  "Wlamir",
  "Yago",
  "Yan",
  "Yuri",
  "Zacarias",
  "Zenildo",
  "Zenon",
  "Adriana",
  "Adriene",
  "Aline",
  "Alice",
  "Aldenir",
  "Aldineia",
  "Almerinda",
  "Aluisia",
  "Alzira",
  "Amanda",
  "Amalia",
  "Am\u00e9lia",
  "Andreia",
  "Andr\u00e9ia",
  "Anelise",
  "Andrea",
  "Andr\u00e9a",
  "Angela",
  "\u00c2ngela",
  "Ang\u00e9lica",
  "Anita",
  "Antonia",
  "Ant\u00f4nia",
  "Aparecida",
  "Arlete",
  "Aurora",
  "Auxiliadora",
  "B\u00e1rbara",
  "Barbara",
  "Beatriz",
  "Benedita",
  "Benilde",
  "Berenice",
  "Bernadete",
  "Branca",
  "Bruna",
  "Camila",
  "Carla",
  "Carmen",
  "Carolina",
  "Carol",
  "Catarina",
  "Cassia",
  "C\u00e1ssia",
  "Cec\u00edlia",
  "Celeste",
  "Celia",
  "C\u00e9lia",
  "Cibele",
  "Cintia",
  "C\u00edntia",
  "Clara",
  "Clarice",
  "Cl\u00e1udia",
  "Claudia",
  "Cleide",
  "Cleia",
  "Cl\u00e9ia",
  "Cleonice",
  "Cristiane",
  "Cristina",
  "Daiane",
  "Daiana",
  "D\u00e1lia",
  "Dalila",
  "Daniela",
  "Danielle",
  "Daniella",
  "Dayana",
  "D\u00e9bora",
  "Debora",
  "Delfina",
  "Denise",
  "Diana",
  "Dilma",
  "Dilza",
  "Dirce",
  "Doralice",
  "Dora",
  "Doris",
  "Dorot\u00e9ia",
  "Dulce",
  "Edilene",
  "Edinea",
  "Edna",
  "Edileuza",
  "Eliana",
  "Elaine",
  "Eliete",
  "Eliza",
  "Elizabete",
  "Elisabete",
  "Elizete",
  "Elma",
  "Elo\u00e1",
  "Eloisa",
  "Elsa",
  "Eluana",
  "Elvira",
  "Emanuela",
  "Emilia",
  "Em\u00edlia",
  "Erica",
  "\u00c9rica",
  "Erika",
  "Esmeralda",
  "Estef\u00e2nia",
  "Esther",
  "Eunice",
  "Eva",
  "Evelyn",
  "Fabiana",
  "Fabiola",
  "F\u00e1tima",
  "Felicidade",
  "Fernanda",
  "Filomena",
  "Fl\u00e1via",
  "Flora",
  "Florinda",
  "Francisca",
  "Gabriela",
  "Geni",
  "Genoveva",
  "Geralda",
  "Gerusa",
  "Gilda",
  "Gilmara",
  "Gisele",
  "Giselle",
  "Giovana",
  "Glauce",
  "Glaucia",
  "Gl\u00e1ucia",
  "Gloria",
  "Gl\u00f3ria",
  "Gra\u00e7a",
  "Graziela",
  "Graziella",
  "Helen",
  "Helena",
  "Helga",
  "Heloisa",
  "Helo\u00edsa",
  "Iara",
  "Ida",
  "I\u00eada",
  "Ilda",
  "Ines",
  "In\u00eas",
  "Iolanda",
  "Irene",
  "Iria",
  "Iris",
  "\u00cdris",
  "Isabel",
  "Isabela",
  "Isabella",
  "Isadora",
  "Iva",
  "Ivani",
  "Ivete",
  "Ivone",
  "Janaina",
  "Jana\u00edna",
  "Janete",
  "Jandira",
  "Janice",
  "Jaqueline",
  "Joana",
  "Josefa",
  "Joelma",
  "Joice",
  "Jordana",
  "Josiane",
  "Joyce",
  "Ju\u00e7ara",
  "Judite",
  "J\u00falia",
  "Juliana",
  "Juliane",
  "Juliene",
  "Karen",
  "Karina",
  "Karoline",
  "K\u00e1tia",
  "Katia",
  "Keila",
  "Keith",
  "Keli",
  "Kelly",
  "Larissa",
  "Laudelina",
  "Laura",
  "Lavinia",
  "Lav\u00ednia",
  "Lea",
  "L\u00e9a",
  "Leandra",
  "Leda",
  "Leila",
  "Leny",
  "Leonice",
  "Leonor",
  "Let\u00edcia",
  "Lia",
  "Liana",
  "Lidiana",
  "Lidia",
  "L\u00eddia",
  "Liliana",
  "Liliane",
  "Lilian",
  "Lilia",
  "Lina",
  "Linda",
  "Lindalva",
  "Linete",
  "Lisa",
  "L\u00edvia",
  "Livia",
  "Lorena",
  "Loraine",
  "Lourdes",
  "Luana",
  "Luc\u00e9lia",
  "L\u00facia",
  "Luciane",
  "Luciene",
  "Luiza",
  "Lu\u00edsa",
  "Luma",
  "Lurdes",
  "Lygia",
  "Magali",
  "Magda",
  "Ma\u00edra",
  "Maira",
  "Manuela",
  "Manuella",
  "Marcela",
  "M\u00e1rcia",
  "Marcia",
  "Margarida",
  "Mariah",
  "Marian",
  "Mariana",
  "Maricelma",
  "Marilda",
  "Marilene",
  "Mar\u00edlia",
  "Marina",
  "Marinete",
  "Marisa",
  "Marlene",
  "Marli",
  "Marta",
  "Mary",
  "Matilde",
  "Mauricia",
  "M\u00e9rcia",
  "Michele",
  "Michelle",
  "Milena",
  "Milene",
  "Mirella",
  "Mirian",
  "Mirtes",
  "Monalisa",
  "M\u00f4nica",
  "Monica",
  "Nadia",
  "N\u00e1dia",
  "Naiara",
  "Nalva",
  "Nancy",
  "Nat\u00e1lia",
  "Natalia",
  "Natalie",
  "Nath\u00e1lia",
  "Nathalia",
  "Nazar\u00e9",
  "Neide",
  "Nelci",
  "Neli",
  "Nelma",
  "Neusa",
  "Neuza",
  "Nice",
  "Nicole",
  "Nilma",
  "Nilza",
  "Nina",
  "Niura",
  "Norma",
  "Nubia",
  "N\u00fabia",
  "Olga",
  "Olinda",
  "Ol\u00edvia",
  "Onilda",
  "Ot\u00edlia",
  "Pamela",
  "P\u00e2mela",
  "Patricia",
  "Patr\u00edcia",
  "Paula",
  "Paulina",
  "Penha",
  "Perla",
  "Pietra",
  "Pilar",
  "Polyana",
  "Priscila",
  "Quit\u00e9ria",
  "Rachel",
  "Rafaela",
  "Raissa",
  "Raquel",
  "Rebeca",
  "Regiane",
  "Regina",
  "Renata",
  "Rita",
  "Roberta",
  "Robertina",
  "Roni",
  "Rosa",
  "Rosalia",
  "Ros\u00e1lia",
  "Rosana",
  "Rosane",
  "Rosangela",
  "Ros\u00e2ngela",
  "Roseli",
  "Roselia",
  "Ros\u00e9lia",
  "Roselina",
  "Rosem\u00e9ri",
  "Rosemeire",
  "Rosilda",
  "Rosilene",
  "Roxana",
  "Rubia",
  "R\u00fabia",
  "Sabina",
  "Sabrina",
  "Salete",
  "Samanta",
  "Samara",
  "Sandra",
  "Sara",
  "Saturnina",
  "Selma",
  "Sheila",
  "Shirley",
  "Sidn\u00e9ia",
  "Silmara",
  "Silvana",
  "Silvania",
  "Silvia",
  "S\u00edlvia",
  "Simone",
  "Sinara",
  "Sirlei",
  "Sirley",
  "Sofia",
  "Solange",
  "Solenir",
  "Soraia",
  "Soraya",
  "Sueli",
  "Suely",
  "Suelen",
  "Susan",
  "Susana",
  "Suzana",
  "Suzane",
  "Suzy",
  "Sylvia",
  "T\u00e1bata",
  "Tain\u00e1",
  "Talita",
  "Tamara",
  "Tania",
  "T\u00e2nia",
  "Tatiana",
  "Tatiane",
  "Telma",
  "Teresa",
  "Teresinha",
  "Tereza",
  "Terezinha",
  "Tha\u00eds",
  "Thais",
  "Thaisa",
  "Thauane",
  "Thelma",
  "Trindade",
  "\u00darsula",
  "Valdete",
  "Val\u00e9ria",
  "Valeria",
  "Valqu\u00edria",
  "Vanda",
  "V\u00e2nia",
  "Vania",
  "Vanessa",
  "Vera",
  "Verena",
  "Ver\u00f4nica",
  "Vilma",
  "Vin\u00e9a",
  "Violeta",
  "Virginia",
  "Virg\u00ednia",
  "Vit\u00f3ria",
  "Vivian",
  "Viviane",
  "Wanda",
  "Yara",
  "Zilda",
  "Zo\u00e9",
  "Zoraide",
  "Zulmira",
  "Maria Eduarda",
  "Maria Clara",
  "Maria Helena",
  "Maria Luiza",
  "Maria Fernanda",
  "Maria J\u00falia",
  "Maria Vit\u00f3ria",
  "Maria Cec\u00edlia",
  "Maria Ant\u00f4nia",
  "Maria Alice",
  "Maria Sophia",
  "Maria Laura",
  "Maria Beatriz",
  "Maria Jos\u00e9",
  "Maria Aparecida",
  "Maria do Carmo",
  "Maria das Gra\u00e7as",
  "Maria de F\u00e1tima",
  "Maria L\u00facia",
  "Maria das Dores",
  "Maria de Lourdes",
  "Maria Auxiliadora",
  "Maria Cristina",
  "Maria Concei\u00e7\u00e3o",
  "Jo\u00e3o Pedro",
  "Jo\u00e3o Vitor",
  "Jo\u00e3o Victor",
  "Jo\u00e3o Lucas",
  "Jo\u00e3o Gabriel",
  "Jo\u00e3o Miguel",
  "Jo\u00e3o Paulo",
  "Jo\u00e3o Vinicius",
  "Jo\u00e3o Felipe",
  "Jo\u00e3o Marcos",
  "Jo\u00e3o Carlos",
  "Jo\u00e3o Henrique",
  "Jo\u00e3o Eduardo",
  "Jo\u00e3o Ant\u00f4nio",
  "Jo\u00e3o Luiz",
  "Jo\u00e3o Batista",
  "Jo\u00e3o Guilherme",
  "Jo\u00e3o Davi",
  "Jo\u00e3o Daniel",
  "Jo\u00e3o Bosco",
  "Pedro Henrique",
  "Pedro Lucas",
  "Pedro Miguel",
  "Pedro Paulo",
  "Pedro Augusto",
  "Pedro Ant\u00f4nio",
  "Luiz Gustavo",
  "Luiz Fernando",
  "Luiz Felipe",
  "Luiz Ot\u00e1vio",
  "Luiz Henrique",
  "Luiz Carlos",
  "Luiz Eduardo",
  "Luiz Ant\u00f4nio",
  "Luiz Paulo",
  "Luiz Gonzaga",
  "Jos\u00e9 Carlos",
  "Jos\u00e9 Antonio",
  "Jos\u00e9 Ant\u00f4nio",
  "Jos\u00e9 Roberto",
  "Jos\u00e9 Eduardo",
  "Jos\u00e9 Augusto",
  "Jos\u00e9 Maria",
  "Jos\u00e9 Luiz",
  "Jos\u00e9 Paulo",
  "Jos\u00e9 Henrique",
  "Jos\u00e9 Francisco",
  "Jos\u00e9 Ricardo",
  "Jos\u00e9 Alberto",
  "Jos\u00e9 Mauricio",
  "Jos\u00e9 Renato",
  "Ana Carolina",
  "Ana Beatriz",
  "Ana Clara",
  "Ana Cl\u00e1udia",
  "Ana Cristina",
  "Ana J\u00falia",
  "Ana Laura",
  "Ana Let\u00edcia",
  "Ana L\u00edvia",
  "Ana Luiza",
  "Ana Maria",
  "Ana Paula",
  "Ana Sophia",
  "Ana Vit\u00f3ria",
  "Ana Carla",
  "Ana L\u00facia",
  "Ana Fl\u00e1via",
  "Ana Karolina",
  "Carlos Eduardo",
  "Carlos Alberto",
  "Carlos Henrique",
  "Carlos Roberto",
  "Carlos Augusto",
  "Carlos Ant\u00f4nio",
  "Carlos Magno",
  "Marcos Ant\u00f4nio",
  "Marcos Vin\u00edcius",
  "Marcos Paulo",
  "Marcos Aur\u00e9lio",
  "Marcos T\u00falio",
  "Marcos Cesar",
  "Marcos Roberto",
  "Paulo Henrique",
  "Paulo Cesar",
  "Paulo C\u00e9sar",
  "Paulo Roberto",
  "Paulo S\u00e9rgio",
  "Paulo Vitor",
  "Paulo Fernando",
  "Paulo Eduardo",
  "Paulo Ricardo",
  "Ant\u00f4nio Carlos",
  "Ant\u00f4nio Marcos",
  "Ant\u00f4nio Paulo",
  "Ant\u00f4nio Jos\u00e9",
  "Ant\u00f4nio Augusto",
  "Ant\u00f4nio S\u00e9rgio",
  "Vitor Hugo",
  "Victor Hugo",
  "Vitor Gabriel",
  "Victor Gabriel",
  "Rafael Augusto",
  "Rafael Henrique",
  "Rafael Fernando",
];

export const BR_SURNAMES: readonly string[] = [
  "Silva",
  "Santos",
  "Souza",
  "Oliveira",
  "Pereira",
  "Lima",
  "Carvalho",
  "Ferreira",
  "Rodrigues",
  "Almeida",
  "Costa",
  "Gomes",
  "Martins",
  "Araujo",
  "Ribeiro",
  "Alves",
  "Monteiro",
  "Mendes",
  "Barros",
  "Freitas",
  "Cardoso",
  "Reis",
  "Rocha",
  "Dias",
  "Nascimento",
  "Andrade",
  "Moreira",
  "Cavalcanti",
  "Cavalcante",
  "Ramos",
  "Vieira",
  "Moraes",
  "Castro",
  "Campos",
  "Teixeira",
  "Correia",
  "Correa",
  "Pinto",
  "Cunha",
  "Melo",
  "Mello",
  "Macedo",
  "Nunes",
  "Marques",
  "Tavares",
  "Barbosa",
  "Lopes",
  "S\u00e1",
  "Vasconcelos",
  "Aguiar",
  "Coelho",
  "Borges",
  "Batista",
  "Bastos",
  "Sales",
  "Saraiva",
  "Soares",
  "Domingues",
  "Pacheco",
  "Cordeiro",
  "Pires",
  "Antunes",
  "Caldas",
  "Brito",
  "Bandeira",
  "Maia",
  "Bezerra",
  "Pessoa",
  "Padilha",
  "Magalh\u00e3es",
  "Pinheiro",
  "Galv\u00e3o",
  "Toledo",
  "Tolentino",
  "Barreto",
  "Bittencourt",
  "Ferraz",
  "Ant\u00e3o",
  "Arag\u00e3o",
  "Arruda",
  "Brand\u00e3o",
  "Camargo",
  "Caminha",
  "Carneiro",
  "Cerqueira",
  "Coutinho",
  "Diniz",
  "Esteves",
  "Fagundes",
  "Falc\u00e3o",
  "Farias",
  "Faria",
  "Figueiredo",
  "Fonseca",
  "Fontes",
  "Fraga",
  "Freire",
  "Furtado",
  "Gama",
  "Garcia",
  "Godinho",
  "Godoi",
  "God\u00f3i",
  "Gon\u00e7alves",
  "Guedes",
  "Guerra",
  "Guimar\u00e3es",
  "Henriques",
  "Holanda",
  "Jorge",
  "Junqueira",
  "Lacerda",
  "Leal",
  "Leite",
  "Lemos",
  "Lessa",
  "Linhares",
  "Lobato",
  "Lobo",
  "Louren\u00e7o",
  "Luz",
  "Maciel",
  "Maranh\u00e3o",
  "Marcondes",
  "Mariano",
  "Martinho",
  "Mascarenhas",
  "Mata",
  "Matias",
  "Matos",
  "Maur\u00edcio",
  "Medeiros",
  "Medina",
  "Meirelles",
  "Menezes",
  "Mesquita",
  "Miranda",
  "Modesto",
  "Mol",
  "Montenegro",
  "Montes",
  "Morais",
  "Mota",
  "Motta",
  "Moura",
  "Munhoz",
  "Nasser",
  "Naz\u00e1rio",
  "Negr\u00e3o",
  "Neto",
  "Neves",
  "Nogueira",
  "Nor\u00f5es",
  "Novaes",
  "Olinda",
  "Onofre",
  "P\u00e1dua",
  "Paes",
  "Paix\u00e3o",
  "Pamplona",
  "Paranhos",
  "Parreira",
  "Passos",
  "Patroc\u00ednio",
  "Paula",
  "Pedrosa",
  "Peixoto",
  "Penha",
  "Penteado",
  "Peixe",
  "Pe\u00e7anha",
  "Pessanha",
  "Petri",
  "Pignatari",
  "Pina",
  "Pinho",
  "Pizarro",
  "Pizzato",
  "Polaco",
  "Pontes",
  "Porto",
  "Prado",
  "Quaresma",
  "Quintela",
  "Rabelo",
  "Ramalho",
  "Rezende",
  "Rios",
  "Rosa",
  "Rufino",
  "Sabino",
  "Sacramento",
  "Salgado",
  "Salim",
  "Sampaio",
  "Sant'Anna",
  "Schmidt",
  "Schneider",
  "Sequeira",
  "Serafim",
  "Sequinel",
  "Severo",
  "Sousa",
  "Souto",
  "Tom\u00e9",
  "Trist\u00e3o",
  "Trindade",
  "Uchoa",
  "Uch\u00f4a",
  "Vaz",
  "Velasco",
  "Veiga",
  "Veloso",
  "Verissimo",
  "Ver\u00edssimo",
  "Viana",
  "Vilar",
  "Vilhena",
  "Vilas",
  "Boas",
  "Volpi",
  "Werneck",
  "Wolf",
  "Xavier",
  "Zaccaria",
  "Zambon",
  "Zanetti",
  "Zanin",
  "Ziviani",
  "Zuza",
];
