-- Step 1: Clean up existing data
DELETE FROM order_items WHERE product_id IN (SELECT id FROM products);
DELETE FROM open_bottles;
DELETE FROM sangria_items;
DELETE FROM products;
DELETE FROM categories WHERE is_special = false;

-- Step 2: Create categories and insert products
DO $$
DECLARE
  cat_0 uuid;
  cat_1 uuid;
  cat_2 uuid;
  cat_3 uuid;
  cat_4 uuid;
  cat_5 uuid;
  cat_6 uuid;
  cat_7 uuid;
  cat_8 uuid;
  cat_9 uuid;
  cat_10 uuid;
  cat_11 uuid;
  cat_12 uuid;
  cat_13 uuid;
  cat_14 uuid;
  cat_15 uuid;
  cat_16 uuid;
  cat_17 uuid;
  cat_18 uuid;
BEGIN

  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Cachaças', 1, true, false) RETURNING id INTO cat_0;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Caipi Ice', 2, true, false) RETURNING id INTO cat_1;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Cervejas', 3, true, false) RETURNING id INTO cat_2;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Corotes Drinks', 4, true, false) RETURNING id INTO cat_3;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Diversos', 5, true, false) RETURNING id INTO cat_4;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Doces', 6, true, false) RETURNING id INTO cat_5;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Energéticos', 7, true, false) RETURNING id INTO cat_6;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Gelos', 8, true, false) RETURNING id INTO cat_7;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Gins', 9, true, false) RETURNING id INTO cat_8;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Ices', 10, true, false) RETURNING id INTO cat_9;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Licores', 11, true, false) RETURNING id INTO cat_10;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Refrigerantes', 12, true, false) RETURNING id INTO cat_11;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Salgadinhos', 13, true, false) RETURNING id INTO cat_12;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Sucos', 14, true, false) RETURNING id INTO cat_13;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Tabacaria e Cigarros', 15, true, false) RETURNING id INTO cat_14;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Vinhos', 16, true, false) RETURNING id INTO cat_15;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Vodkas', 17, true, false) RETURNING id INTO cat_16;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Whiskys', 18, true, false) RETURNING id INTO cat_17;
  INSERT INTO categories (name, sort_order, is_active, is_special) VALUES ('Água', 19, true, false) RETURNING id INTO cat_18;

  -- Step 3: Insert products
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('51 ice 0% ALCOOL', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('51 Ice Kiwi', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('51 Ice Limão', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('51 Ice Maracujá', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('51 Ice Morango', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Água 1,5L', NULL, 6.5, 4.55, 42.9, 10, true, false, cat_18, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Água 500ml', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_18, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Água com Gás', NULL, 4.5, 3.15, 42.9, 10, true, false, cat_18, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Água de Coco 1L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Amstel 269ml', NULL, 5.0, 2.4, 108.3, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Baly 2 Litros', NULL, 16.0, 9.6, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Big Boss 2 Litros', NULL, 10.0, 7.0, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Bis Branco', NULL, 10.0, 7.0, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Bis Preto', NULL, 10.0, 7.0, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cachaça 51 1L', NULL, 24.5, 14.7, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Limão', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Camisinha', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cantinho do Vale 2L', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_15, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cantinho do Vale 880ml', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_15, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Canudo Rosa ou Preto', NULL, 2.5, 1.75, 42.9, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Carvão de Churrasco 2kg', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Chevette - Corote limão, gelo de coco e suco baunilha', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Chopp de Vinho Draft 600ml', NULL, 17.0, 10.2, 66.7, 10, true, false, cat_15, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola 1L', NULL, 10.0, 7.0, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola 200ml', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola 2L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola 600ml', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola Lata 350ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola Zero 1L', NULL, 10.0, 7.0, 42.9, 10, false, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola Zero 200ml', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola Zero 2L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Coca-Cola Zero 600ml', NULL, 8.0, 5.6, 42.9, 10, false, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Copo 700ml', NULL, 2.5, 1.75, 42.9, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('CupNoodles Carne', NULL, 13.5, 8.1, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('CupNoodles Galinha', NULL, 13.5, 8.1, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Dani 700ml', NULL, 27.0, 16.2, 66.7, 10, true, false, cat_15, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Dom Nogueira 900ml', NULL, 22.0, 13.2, 66.7, 10, true, false, cat_15, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Eight', NULL, 6.5, 4.55, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fanta Laranja 2L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fofura Cebola', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fofura Churrasco', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fofura Presunto', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fofura Queijo', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fofura Requeijão', NULL, 6.0, 4.2, 42.9, 10, false, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fusion 2 Litros', NULL, 24.5, 14.7, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Comum 5kg', NULL, 25.0, 9.0, 177.8, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Bulldog', NULL, 158.5, 79.25, 100.0, 10, false, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Gordons Rosa', NULL, 95.0, 47.5, 100.0, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Gordons Tradicional', NULL, 95.0, 47.5, 100.0, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Intencion Rosa', NULL, 27.0, 16.2, 66.7, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Intencion Tradicional', NULL, 27.0, 16.2, 66.7, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Ópera Melancia', NULL, 25.0, 15.0, 66.7, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Ópera Rosa', NULL, 25.0, 15.0, 66.7, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Rocks Rosa', NULL, 38.0, 20.9, 81.8, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Rocks Seco', NULL, 38.0, 20.9, 81.8, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Guaraná Antarctica 600ml', NULL, 7.5, 5.25, 42.9, 10, false, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Guaraná Antatica 2L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Guaranita 600ml', NULL, 7.5, 5.25, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Halls Melancia', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Halls Menta', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Halls Morango', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Halls Preto', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Keep Cooler', NULL, 13.5, 8.1, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor 43 Baristo', NULL, 215.0, 107.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor 43 Chocolate', NULL, 215.0, 107.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor 43 Creme Brulé', NULL, 215.0, 107.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor 43 Tradicional', NULL, 175.0, 87.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Amarula Chocolate Raspberry', NULL, 149.0, 74.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Amarula Ethiopian Coffee', NULL, 230.5, 115.25, 100.0, 10, false, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Amarula Raspberry', NULL, 230.5, 115.25, 100.0, 10, false, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Amarula Tradicional', NULL, 145.0, 72.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Amarula Vanilla Spice', NULL, 149.0, 74.5, 100.0, 10, false, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Dolce di Latte', NULL, 69.0, 34.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Fino de Tangerina', NULL, 69.0, 34.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Stock Cacau', NULL, 49.0, 24.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Licor Stock Morango Creme', NULL, 49.0, 24.5, 100.0, 10, true, false, cat_10, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Malboro', NULL, 13.0, 9.1, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Malboro Azul', NULL, 13.0, 9.1, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Malboro Verde', NULL, 13.0, 9.1, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Monster 473ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Monster Mango Loco 473ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Monster Pipeline Punch 473ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Monster The Doctor 473ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Monster Zero Sugar 473ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Narguile Completo', NULL, 20.0, 5.0, 300.0, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Old Spice Energetico 2 Litros', NULL, 16.0, 9.6, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Old Spice Lata 269ml', NULL, 5.0, 3.5, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Original 300ml', NULL, 6.0, 3.6, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Paçoca', NULL, 2.0, 1.4, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Palheiro Paulistinha', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Banana Caramelizada', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Baunilha', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Caramelo', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Cereja', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Chocolate Belga', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Doce de Leite', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Peaky Blinders Mel', NULL, 65.0, 32.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Petra Escura 600ml', NULL, 17.5, 10.5, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Petra Origem 300ml', NULL, 6.5, 3.9, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Petra Puro Malte 600ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Red Bull Energy Drink 250ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Red Bull Energy Drink 355ml', NULL, 17.0, 10.2, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Red Bull Zero 250ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ruffles 45g', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ruffles Cebola e Salsa 45g', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ruffles Churrasco 45g', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Bacon', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Calabresa', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Churrasco', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Pimenta Mexicana', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Presunto', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sakata Queijo', NULL, 3.5, 2.45, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Salgadinho Pippos Queijo 55g', NULL, 5.0, 3.5, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Schweppes Citrus 350ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Schweppes Tonica 350ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Skol 269ml', NULL, 4.0, 2.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Skol Puro Malte 269ml', NULL, 5.0, 3.0, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff 998ml', NULL, 44.0, 22.0, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Citrus 998ml', NULL, 44.0, 22.0, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Green Apple 998ml', NULL, 44.0, 22.0, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Ice 275ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Ice Limão Siciliano 275ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Watermelon 998ml', NULL, 44.0, 22.0, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff X1 Açaí', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff X1 Guaraná', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sprite 2L', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Sprite Lata 350ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Steck 2L', NULL, 16.0, 9.6, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Baunilha 1L', NULL, 10.0, 6.0, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Citrus Concentrado 500ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Cranberry 1L', NULL, 21.0, 12.6, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco De Laranja 1L', NULL, 13.5, 8.1, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco de Limão Concentrado 500ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Manga 1L', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Maracujá 1L', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Pessego 1L', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Suco Uva 1L', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_13, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco 7 Mares', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco Boss', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco Hi', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco Raw', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco Raw Menthol', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tabaco Ziggy', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tanqueray 750ml', NULL, 149.5, 74.75, 100.0, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tanqueray Sevilla 750ml', NULL, 169.5, 84.75, 100.0, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tequila José Cuervo Gold 750ml', NULL, 155.0, 77.5, 100.0, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tequila José Cuervo Silver 750ml', NULL, 155.0, 77.5, 100.0, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tereré Hortelã', NULL, 20.0, 12.0, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tereré Menta', NULL, 20.0, 12.0, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('TNT 2L', NULL, 16.0, 9.6, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('TNT Lata 269ml', NULL, 5.0, 3.5, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('TNT Lata Açaí 473ml', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('TNT Lata Tangerina 473ml', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('TNT Mango Lata 473ml', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tortuguita Ao Leite', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Tortuguita Branca', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Trident', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Absolut 750ml', NULL, 89.0, 44.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Absolut Vanilla 750ml', NULL, 89.0, 44.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Balalaika 998ml', NULL, 24.5, 12.25, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Ciroc 750ml', NULL, 175.0, 87.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Ciroc Mango 700ml', NULL, 175.0, 87.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Grey Goose 750ml', NULL, 269.0, 134.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Intencion 900ml', NULL, 22.0, 13.2, 66.7, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Natasha 900ml', NULL, 23.0, 13.8, 66.7, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Orloff 998ml', NULL, 37.0, 18.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Skyy 980ml', NULL, 55.0, 27.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Vodka Skyy Raspberry 980ml', NULL, 55.0, 27.5, 100.0, 10, true, false, cat_16, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Ballantines 1L', NULL, 99.0, 49.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Black Label 750ml', NULL, 189.0, 94.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Black Stone 1L', NULL, 45.0, 22.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Chivas 750ml', NULL, 185.0, 92.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Grants 1L', NULL, 89.0, 44.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Jack Daniels 1L', NULL, 189.0, 94.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Jack Daniels Apple 1L', NULL, 195.0, 97.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Jack Daniels Fire 1L', NULL, 195.0, 97.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Jack Daniels Honey 1L', NULL, 195.0, 97.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Jim Beam 1L', NULL, 99.0, 49.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Old Parr 1L', NULL, 229.0, 114.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Passport 1L', NULL, 69.0, 34.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Red Label 1L', NULL, 119.0, 59.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky Teachers 1L', NULL, 79.0, 39.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Whisky White Horse 1L', NULL, 79.0, 39.5, 100.0, 10, true, false, cat_17, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ypióca 900ml', NULL, 22.0, 13.2, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Comum 2kg', NULL, 12.0, 6.0, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Coco 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Comum 1kg', NULL, 7.0, 3.5, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Coco 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Pessego', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Limão', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Tutti-Frutti', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Blue', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Morango', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Blueberry', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Tradicional', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Heineken 350ml', NULL, 7.5, 4.5, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Heineken 600ml', NULL, 17.5, 10.5, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Heineken Long Neck 330ml', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Budweiser 269ml', NULL, 5.0, 3.0, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Budweiser 600ml', NULL, 13.0, 7.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Budweiser Long Neck 330ml', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Corona 330ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Stella Artois 275ml', NULL, 7.5, 4.5, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Stella Artois 600ml', NULL, 17.0, 10.2, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Brahma Duplo Malte 269ml', NULL, 4.5, 2.7, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Brahma Duplo Malte 600ml', NULL, 13.0, 7.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Spaten 600ml', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Spaten 269ml', NULL, 5.0, 3.0, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Amstel 600ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Colorado Appia 600ml', NULL, 18.0, 10.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Eisenbahn Pilsen 355ml', NULL, 7.5, 4.5, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Beck''s 330ml', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Skol 600ml', NULL, 11.0, 6.6, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Brahma 600ml', NULL, 11.0, 6.6, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Itaipava 600ml', NULL, 11.0, 6.6, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Itaipava 269ml', NULL, 3.5, 2.1, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Brahma 269ml', NULL, 4.0, 2.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Devassa 269ml', NULL, 4.0, 2.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Eisenbahn Weizen 600ml', NULL, 18.0, 10.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ice 51 Balada', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Smirnoff Ice Green Apple 275ml', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_9, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Maçã Verde', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Schweppes Ginger Ale 350ml', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fanta Uva 2L', NULL, 14.5, 8.7, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fanta Laranja 600ml', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Guaraná Antarctica 2L', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Guaraná Antarctica Lata 350ml', NULL, 5.5, 3.85, 42.9, 10, true, false, cat_11, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Morango', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Maracujá', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Abacaxi', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Frutas Vermelhas', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Caip ice Kiwi', NULL, 35.0, 19.25, 81.8, 10, true, true, cat_1, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Old Spice Energetico Lata 473ml', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Fusion Lata 310ml', NULL, 9.0, 5.4, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Red Bull Tropical 250ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Mega Drive - Corote morango, gelo coco e energetico', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Lamborghini - Corote blue, gelo coco e energetico', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Ferrari - Corote pessego, gelo coco e energetico', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Camaro - Corote tutti, gelo coco e suco citrus', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Porsche - Corote blueberry, gelo coco e energetico', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Mustang - Corote maçã verde, gelo coco e energetico', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Morango 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Morango 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Limão 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Limão 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Maracujá 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Maracujá 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Abacaxi 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Abacaxi 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Frutas Vermelhas 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Frutas Vermelhas 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Uva 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Uva 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Opera Tropical', NULL, 25.0, 15.0, 66.7, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Heineken 0% 330ml', NULL, 8.5, 5.1, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Essência de Narguile Sabores', NULL, 10.0, 5.0, 100.0, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Carvão de Narguile', NULL, 5.0, 2.5, 100.0, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Seda', NULL, 3.0, 2.1, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Piteira', NULL, 3.0, 2.1, 42.9, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Isqueiro', NULL, 6.0, 3.6, 66.7, 10, true, false, cat_14, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Pé de Moleque', NULL, 3.0, 2.1, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Mentos Fresh', NULL, 4.0, 2.8, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Kit Kat', NULL, 8.0, 5.6, 42.9, 10, true, false, cat_5, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Wals Session Citra IPA 600ml', NULL, 22.0, 13.2, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Wals Trippel 600ml', NULL, 24.0, 14.4, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Wals Witbier 600ml', NULL, 22.0, 13.2, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Combo Breja + Salgadinho', NULL, 12.0, 7.2, 66.7, 10, true, false, cat_4, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Red Bull Summer Edition Juneberry 250ml', NULL, 14.0, 8.4, 66.7, 10, true, false, cat_6, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Doritos Queijo 48g', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Macacos Me Mordam - Corote tradicional, gelo e suco baunilha', NULL, 10.0, 7.0, 42.9, 10, true, true, cat_3, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cerveja Patagonia Amber Lager 740ml', NULL, 18.0, 10.8, 66.7, 10, true, false, cat_2, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Lays Presunto 47g', NULL, 7.0, 4.9, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Kiwi 2kg', NULL, 14.5, 7.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gelo Kiwi 1kg', NULL, 8.5, 4.25, 100.0, 10, true, false, cat_7, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Gin Rocks Maça Verde', NULL, 38.0, 20.9, 81.8, 10, true, false, cat_8, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Salsicha Assada Bacon', NULL, 6.0, 3.6, 66.7, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Salsicha Assada Cheddar', NULL, 6.0, 3.6, 66.7, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Salsicha Assada Tradicional', NULL, 6.0, 3.6, 66.7, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cheetos Bola 37g', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Cheetos Lua 40g', NULL, 6.0, 4.2, 42.9, 10, true, false, cat_12, NULL);
  INSERT INTO products (name, description, sale_price, cost_price, profit_margin, stock, is_active, is_prepared, category_id, image_url) VALUES ('Corote Cereja', NULL, 8.0, 4.8, 66.7, 10, true, false, cat_0, NULL);

END $$;